ame: 'AtlasCLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v3

    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        repository: mongodb/mongodb-atlas-cli
        ref: atlascli/v1.5.1

    - name: Build AtlasCLI
      shell: bash
      run: make build-atlascli

    - name: Add AtlasCLI to $PATH
      shell: bash
      run: |
        chmod +x bin/atlas
        echo "$GITHUB_WORKSPACE/bin/atlas"
        echo "$GITHUB_PATH"
        echo "$GITHUB_WORKSPACE/bin/atlas" >> $GITHUB_PATH

    - name: Run AtlasCLI
      shell: bash
      run: atlas --help