ame: 'AtlasCLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
inputs:
  version:
    description: 'AtlasCLI version to use'
    required: false
    default: 'v1.5.1'
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v3

    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        repository: mongodb/mongodb-atlas-cli
        ref: atlascli/${{ inputs.version }}

    - name: Build AtlasCLI
      shell: bash
      run: make build-atlascli

    - name: Add AtlasCLI to $PATH
      shell: bash
      run: |
        chmod +x bin/atlas
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: Run AtlasCLI
      shell: bash
      run: atlas --help