ame: 'AtlasCLI GitHub Action'
description: 'Use AtlasCLI in your GitHub workflow'
inputs:
  version:
    description: 'AtlasCLI version to use'
    required: false
    default: 'v1.5.1'
  public-key:
      description: 'MongoDB Atlas PublicKey'
      required: true
  private-key:
      description: 'MongoDB Atlas PrivateKey'
      required: true
  org-id:
      description: 'MongoDB Atlas Organization ID'
      required: false
  project-id:
      description: 'MongoDB Atlas Project ID'
      required: false
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v3

    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        repository: mongodb/mongodb-atlas-cli
        ref: atlascli/${{ inputs.version }}

    - name: Build AtlasCLI
      shell: bash
      run: make build-atlascli

    - name: Add AtlasCLI to $PATH
      shell: bash
      run: |
        chmod +x bin/atlas
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Configure AtlasCLI
      shell: bash
      run: |
        atlas config set org_id ${{ inputs.org-id }}
        atlas config set project_id ${{ inputs.project-id }}
        atlas config set public_api_key ${{ inputs.public-key }}
        atlas config set private_api_key ${{ inputs.private-key }}
        atlas config set service "cloud"