---
name: Test AtlasCLI Action - Latest Release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  no-version:
    name: Testing AtlasCLI action without providing version
    strategy:
     fail-fast: false
     matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: AtlasCLI
        uses: andreaangiolillo/atlas-cli-github-action@main
        with:
         public-key: ${{ secrets.PUBLIC_KEY }}
         private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Use AtlasCLI
        shell: bash
        run: atlas --help
  with-version:
    name: Testing AtlasCLI action
    strategy:
     fail-fast: false
     matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: AtlasCLI
        uses: actions/atlas-cli-github-action@v1.0.0
        with:
         version: v1.5.0
         public-key: ${{ secrets.PUBLIC_KEY }}
         private-key: ${{ secrets.PRIVATE_KEY }}
         org-id: ${{ vars.ORG_ID }}
         project-id: ${{ vars.PROJECT_ID }}
      - name: Use AtlasCLI
        shell: bash
        run: atlas project ls


