---
name: Test AtlasCLI Action on a GitHub Action
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    name: AtlasCLI
    steps:
      - name: AtlasCLI
        uses: andreaangiolillo/atlasCLI-github-action@v0.0.4
        with:
          who-to-greet: 'Mona the Octocat'
