---
name: Test AtlasCLI Action
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  no-version:
    name: Testing AtlasCLI action without providing version
    strategy:
     fail-fast: false
     matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: AtlasCLI
        uses: andreaangiolillo/atlas-cli-github-action@main
        with:
         public-key: ${{ secrets.PUBLIC_KEY }}
         private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Use AtlasCLI
        shell: bash
        run: atlas --help
  with-version:
    name: Testing AtlasCLI action
    strategy:
     fail-fast: false
     matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: AtlasCLI
        uses: andreaangiolillo/atlas-cli-github-action@main
        with:
         version: v1.5.0
         public-key: ${{ secrets.PUBLIC_KEY }}
         private-key: ${{ secrets.PRIVATE_KEY }}
         org-id: ${{ env.ORG_ID }}
         project-id: ${{ env.PROJECT_ID }}
      - name: Use AtlasCLI
        shell: bash
        run: atlas project ls
  create-project:
    name: Testing AtlasCLI action
    strategy:
     fail-fast: false
     matrix:
      os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: AtlasCLI
        id: atlas-cli
        uses: andreaangiolillo/atlas-cli-github-action@main
        with:
         version: v1.5.0
         public-key: ${{ secrets.PUBLIC_KEY }}
         private-key: ${{ secrets.PRIVATE_KEY }}
         create-project-id: ${{github.run_id}}
      - name: Delete Project
        shell: bash
        run: atlas project delete ${{ steps.atlas-cli.outputs.create-project-id }} --force
