---
name: Test AtlasCLI Action
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  no-version:
    name: Testing AtlasCLI action without providing version
    strategy:
     fail-fast: false
     matrix:
      os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: TEST_ENV
    steps:
      - name: AtlasCLI
        uses: andreaangiolillo/atlasCLI-github-action@main
        with:
         public-key: ${{ secrets.PUBLIC_KEY }}
         private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Use AtlasCLI
        shell: bash
        run: atlas --help
  with-version:
    name: Testing AtlasCLI action
    strategy:
     fail-fast: false
     matrix:
      os: [ubuntu-latest, macos-latest]
    environment: TEST_ENV
    steps:
      - name: AtlasCLI
        uses: andreaangiolillo/atlasCLI-github-action@main
        with:
         version: v1.5.0
         public-key: ${{ secrets.PUBLIC_KEY }}
         private-key: ${{ secrets.PRIVATE_KEY }}
         org-id: 62669e5cf881800090327a03
         project-id: 63f8c04f967d7649b6e1109e
      - name: Use AtlasCLI
        shell: bash
        run: atlas project ls
