---
name: Test AtlasCLI Action
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ubuntu-latest:
    name: Testing AtlasCLI action without providing version
    runs-on: ubuntu-latest
    steps:
      - name: AtlasCLI
        uses: andreaangiolillo/atlasCLI-github-action@v0.0.4
